name: Deploy to Vercel

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Verify Vercel authentication
        run: |
          vercel whoami \
            --token "${{ secrets.VERCEL_TOKEN }}"

      - name: Link Vercel project
        run: |
          vercel link \
            --yes \
            --project "${{ secrets.VERCEL_PROJECT_ID }}" \
            --scope "team_sMX1olOCelID3PvUTV5rdIKq" \
            --token "${{ secrets.VERCEL_TOKEN }}"

      - name: Pull Vercel environment
        run: |
          vercel pull \
            --yes \
            --environment=production \
            --token "${{ secrets.VERCEL_TOKEN }}"

      - name: Build project
        run: |
          vercel build \
            --prod \
            --token "${{ secrets.VERCEL_TOKEN }}"

      - name: Deploy to Vercel
        run: |
          vercel deploy \
            --prebuilt \
            --prod \
            --token "${{ secrets.VERCEL_TOKEN }}"
